# Generated by Django 3.0.5 on 2020-09-05 07:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0003_advertisement_cartype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='engineType',
            field=models.CharField(choices=[('DIZEL', 'Dizel'), ('BENZIN', 'Benzin'), ('BENZIN+LPG', 'Benzin + LPG')], default='BENZIN', max_length=10),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='API.Region'),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='shifterType',
            field=models.CharField(choices=[('AUTOMATSKI', 'Automatski'), ('RUCNI', 'Rucni')], default='RUCNI', max_length=10),
        ),
        migrations.AlterField(
            model_name='advertisement',
            name='status',
            field=models.CharField(choices=[('AKTIVAN', 'Aktivan'), ('PRODAN', 'Prodan'), ('NEAKTIVAN', 'Neaktivan')], default='AKTIVAN', max_length=10),
        ),
        migrations.AlterField(
            model_name='image',
            name='advertisement',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ads', to='API.Advertisement'),
        ),
        migrations.AlterField(
            model_name='type',
            name='make',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='types', to='API.Make'),
        ),
    ]
