# Generated by Django 3.1.1 on 2020-09-07 14:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0006_auto_20200906_1025'),
        ('API', '0005_merge_20200907_1150'),
    ]

    operations = [
    ]
