# Generated by Django 3.0.5 on 2020-09-06 08:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200904_1448'),
        ('API', '0004_auto_20200905_0906'),
    ]

    operations = [
    ]
