# Generated by Django 3.1.1 on 2020-09-07 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0004_auto_20200904_1448'),
        ('API', '0004_auto_20200905_0906'),
    ]

    operations = [
    ]
