# Generated by Django 3.0.5 on 2020-09-10 05:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0009_auto_20200908_0820'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='advertisement',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='API.Advertisement'),
        ),
        migrations.AlterField(
            model_name='image',
            name='imagePath',
            field=models.ImageField(blank=True, null=True, upload_to='images'),
        ),
    ]
