# Generated by Django 3.0.5 on 2020-09-10 10:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0010_auto_20200910_0748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advertisement',
            name='carType',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='type', to='API.Type'),
        ),
    ]
